import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(appRoot, '..');
const dashboardRoot = path.join(repoRoot, 'dashboard');
const outputPath = path.join(appRoot, 'src', 'data', 'dashboardData.ts');

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        field += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      row.push(field);
      field = '';
      continue;
    }

    if ((char === '\n' || char === '\r') && !inQuotes) {
      if (char === '\r' && next === '\n') {
        i += 1;
      }
      row.push(field);
      if (row.some((value) => value.length > 0)) {
        rows.push(row);
      }
      row = [];
      field = '';
      continue;
    }

    field += char;
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field);
    if (row.some((value) => value.length > 0)) {
      rows.push(row);
    }
  }

  if (rows.length === 0) {
    return [];
  }

  const headers = rows[0];
  return rows.slice(1).map((values) => {
    const record = {};
    headers.forEach((header, index) => {
      record[header] = values[index] ?? '';
    });
    return record;
  });
}

async function readCsv(fileName) {
  const text = await readFile(path.join(dashboardRoot, fileName), 'utf8');
  return parseCsv(text);
}

const [jobPool, applicationLog, appliedArchive, dailyDashboard, blockerQueue, followUp, automationRules, resumeRules] = await Promise.all([
  readCsv('job_pool.csv'),
  readCsv('application_log.csv'),
  readCsv('applied_archive.csv'),
  readCsv('daily_dashboard.csv'),
  readCsv('blocker_queue.csv'),
  readCsv('follow_up.csv'),
  readCsv('automation_rules.csv'),
  readCsv('resume_rules.csv'),
]);

const payload = {
  generatedAt: new Date().toISOString(),
  jobPool,
  applicationLog,
  appliedArchive,
  dailyDashboard,
  blockerQueue,
  followUp,
  automationRules,
  resumeRules,
};

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/sync-data.mjs. Do not edit by hand.\nexport const dashboardData = ${JSON.stringify(payload, null, 2)} as const;\n`,
  'utf8',
);

console.log(`Synced ${jobPool.length} job rows, ${applicationLog.length} application rows, and ${appliedArchive.length} archived rows.`);
