import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(appRoot, '..');
const dashboardRoot = path.join(repoRoot, 'dashboard');
const outputPath = path.join(appRoot, 'src', 'data', 'dashboardData.ts');

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        field += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      row.push(field);
      field = '';
      continue;
    }

    if ((char === '\n' || char === '\r') && !inQuotes) {
      if (char === '\r' && next === '\n') {
        i += 1;
      }
      row.push(field);
      if (row.some((value) => value.length > 0)) {
        rows.push(row);
      }
      row = [];
      field = '';
      continue;
    }

    field += char;
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field);
    if (row.some((value) => value.length > 0)) {
      rows.push(row);
    }
  }

  if (rows.length === 0) {
    return [];
  }

  const headers = rows[0];
  return rows.slice(1).map((values) => {
    const record = {};
    headers.forEach((header, index) => {
      record[header] = values[index] ?? '';
    });
    return record;
  });
}

// The US track lives directly in dashboard/, the China track in dashboard/china/.
// Both use identical headers, so one reader serves both.
const regionRoots = {
  us: dashboardRoot,
  china: path.join(dashboardRoot, 'china'),
};

async function readCsv(root, fileName) {
  try {
    const text = await readFile(path.join(root, fileName), 'utf8');
    return parseCsv(text);
  } catch (error) {
    if (error.code === 'ENOENT') {
      return [];
    }
    throw error;
  }
}

async function readRegion(root) {
  const [jobPool, applicationLog, appliedArchive, dailyDashboard, blockerQueue, followUp, automationRules, resumeRules] = await Promise.all([
    readCsv(root, 'job_pool.csv'),
    readCsv(root, 'application_log.csv'),
    readCsv(root, 'applied_archive.csv'),
    readCsv(root, 'daily_dashboard.csv'),
    readCsv(root, 'blocker_queue.csv'),
    readCsv(root, 'follow_up.csv'),
    readCsv(root, 'automation_rules.csv'),
    readCsv(root, 'resume_rules.csv'),
  ]);

  return { jobPool, applicationLog, appliedArchive, dailyDashboard, blockerQueue, followUp, automationRules, resumeRules };
}

const [us, china] = await Promise.all([readRegion(regionRoots.us), readRegion(regionRoots.china)]);

const payload = {
  generatedAt: new Date().toISOString(),
  regions: { us, china },
};

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/sync-data.mjs. Do not edit by hand.\nexport const dashboardData = ${JSON.stringify(payload, null, 2)};\n`,
  'utf8',
);

console.log(
  `Synced US: ${us.jobPool.length} job rows, ${us.applicationLog.length} application rows, ${us.appliedArchive.length} archived rows. ` +
    `China: ${china.jobPool.length} job rows, ${china.applicationLog.length} application rows, ${china.appliedArchive.length} archived rows.`,
);
